### ISSUE TITLE
Implement shared, global, and meta data structure

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/templating-engine#12]
## To Do

- [x] Implement shared data structure at global and site levels
- [x] Implement global data structure at global and site levels
- [x] Implement meta data structure at global and site levels

**Comment by laurenhamel** [comment]
This will also need to be a placeholder for the time being until we can dump out some real data from the CMS. We'll at least need to replicate the folder structure we're anticipating to be able to continue with development.
