### ISSUE TITLE
Add mechanism(s) for retrieving and loading shared, global, and meta data

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/templating-engine#15]
## To Do

- [x] Create mechanism for retrieving/loading shared data (pulling from all sites plus global level)
- [x] Create mechanism for retrieving/loading global data (pulling from site and global levels)
- [x] Create mechanism for retrieving/loading meta data (pulling from site and global levels)

**Comment by laurenhamel** [comment]
This has been implemented in indexing for the most part. Another layer on top of this, though, will be pulling the data out of the indexed data set and passing it into the page renderer along with the page data.
